services:
  phoenixd:
    build: ..
    image: phoenixd:latest
    container_name: phoenixd
    volumes:
      - phoenixd-data:/phoenix/.phoenix
    command: --agree-to-terms-of-service

volumes:
  phoenixd-data:
