services:
  phoenixd:
    image: ghcr.io/sethforprivacy/phoenixd:latest
    container_name: phoenixd
    user: "${UID}:${GID}"    
    volumes:
      - phoenixd-data:/phoenix/.phoenix
    command: --agree-to-terms-of-service

volumes:
  phoenixd-data:
